package charis.com.smartremotecontrol;


/**
 * Created by Charis on 09-Jun-16.
 */
public enum BUTTON {  NULL, POWER,VOLUME_UP,VOLUME_DOWN,CHANNEL_UP,CHANNEL_DOWN,MUTE,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO,ZOOM,SLEEP,MENU,INFO,RED,GREEN,YELLOW,BLUE,MODE,EXIT,EPG,PLAY,STOP,RECORD,SHIFT,SAT,USB,BAND,FAST_FORWARD,FAST_REWIND,FAV,PAUSE,PAGE_DOWN,PAGE_UP,OK,NEXT,PREVIOUS

}
